- hosts: all
  roles:
    - role: preinstall
  gather_facts: yes
  any_errors_fatal: true
  tags: [preinstall]

- hosts: k8s
  roles:
    - role: k8s
  gather_facts: yes
  any_errors_fatal: true
  tags: [k8s]


- hosts: k8s_masters
  roles:
    - role: join_master
  gather_facts: yes
  any_errors_fatal: true
  tags: [join_master]

