- name: Init cluster | Check if kubeadm has already run
  stat:
    path: "/var/lib/kubelet/config.yaml"
  register: kubeadm_already_run
  when: inventory_hostname == groups['k8s_masters'][0]
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- block:
    - name: Init cluster | Copy kubeadmcnf.yaml
      template:
        src: kubeadmcnf.yml.j2
        dest: /root/kubeadmcnf.yaml

    - name: Init cluster | Initiate cluster on node groups['kube_master'][0]
      shell: kubeadm init --config=/root/kubeadmcnf.yaml
      register: kubeadm_init
      # Retry is because upload config sometimes fails
      until: kubeadm_init is succeeded or "field is immutable" in kubeadm_init.stderr
      notify: Restart kubelet

  when: inventory_hostname == groups['k8s_masters'][0] and not kubeadm_already_run.stat.exists
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- block:
    - name: Create kubectl directory
      file:
        path: /root/.kube
        state: directory

    - name: Configure kubectl
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes

    - name: Fetch kubeconfig
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: kubeconfig/
        flat: yes
  when: inventory_hostname == groups['k8s_masters'][0]
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- name: Sleep for 300 seconds and reboot the Master1 server
  wait_for:
    timeout: 300
  delegate_to: localhost

- name: Reboot the servers
  command: reboot
  async: 1
  poll: 0
  ignore_errors: yes
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- name: Sleep for 300 seconds to Master1 up and running
  wait_for:
    timeout: 300
  delegate_to: localhost

- name: Example Task After Reboot
  debug:
    msg: "Server back online and ready for tasks."

