- name: Disable SWAP since kubernetes can't work with swap enabled
  shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable ufw # just in Ubuntu
  ufw:
    state: disabled

- name: Ensure kernel modules for containerd are enabled
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "{{ item }}"
    create: yes
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Load kernel modules
  command:
    cmd: "modprobe {{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Ensure sysctl settings for Kubernetes are present
  blockinfile:
    path: /etc/sysctl.d/kubernetes.conf
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    owner: root
    group: root
    mode: '0644'

- name: Reload sysctl settings
  command:
    cmd: sysctl --system

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - gpg

    state: present
    update_cache: yes  # Optional: this will also update the cache before installing

- name: Ensure the /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'  # Adjust the permissions as necessary
    owner: root   # Set the owner, if required
    group: root   # Set the group, if required

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0644'

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Remove existing Docker GPG key if it exists
  file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent

- name: Convert the downloaded GPG key to a keyring
  shell:
    cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg < /tmp/docker.gpg
  args:
    executable: /bin/bash
  become: true
  notify:
    - Remove temporary GPG key file

- name: Determine the architecture
  command: dpkg --print-architecture
  register: architecture

- name: Determine the distribution codename
  command: lsb_release -cs
  register: distribution_codename

- name: Add Docker APT repository
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    create: yes
    line: "deb [arch={{ architecture.stdout }} signed-by={{ docker_gpg_key_path }}] https://download.docker.com/linux/ubuntu {{ distribution_codename.stdout }} stable"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages (containerd)
  apt:
    pkg:
      - containerd.io
    state: present
    update_cache: yes  # Optional: this will also update the cache before installing

- name: Ensure containerd is installed before generating its default config
  package:
    name: containerd
    state: present

- name: Generate default containerd configuration
  shell:
    cmd: containerd config default > /etc/containerd/config.toml

- name: Replace SystemdCgroup from false to true in containerd config
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes

- name: Enable containerd service
  systemd:
    name: containerd
    enabled: yes

- name: Ensure the APT keyring directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes APT key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'

- name: Delete the existing Kubernetes APT keyring file if it exists
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent

- name: Import Kubernetes APT key
  shell:
    cmd: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg < /tmp/kubernetes-release.key"

- name: Remove the temporary Kubernetes APT key file
  ansible.builtin.file:
    path: /tmp/kubernetes-release.key
    state: absent

- name: Add Kubernetes repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: kubernetes.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Add hosts to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].private_ip }} {{ item }} {{ item }}.sudoix.com"
    state: present
    create: no
  loop: "{{ groups['all'] }}"
  when: hostvars[item].private_ip is defined

- name: Pull Kubernetes images
  command:
    cmd: kubeadm config images pull


