---
# handlers file for k8s

- name: Remove temporary GPG key file
  file:
    path: "/tmp/docker.list"
    state: absent

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted