# General
install_ansible_modules: "true"
disable_transparent_huge_pages: "true"
setup_interface: "false"

#SSH
ssh_port: 2222

# Network Calico see here for more details https://github.com/projectcalico/calico/releases
calico_operator_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/tigera-operator.yaml"
calico_crd_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.29.0/manifests/custom-resources.yaml"
pod_network_cidr: "192.168.0.0/16"

# DNS
resolv_nameservers: [8.8.8.8, 4.2.2.4] # 403.online

# Sanction shekan
use_iran: "false" # change it to "false" if you are outside of iran

# Docker
docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_gpg_key_path: "/etc/apt/keyrings/docker.gpg"
docker_apt_repo: "https://download.docker.com/linux/ubuntu"

# Kubernetes
kubernetes_gpg_keyring_path: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
kubernetes_gpg_key_url: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key"
kubernetes_apt_repo: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/"
k8s_version: "1.32.2" # see here https://kubernetes.io/releases/patch-releases/ and https://github.com/kubernetes/kubernetes/releases

# CRI
cri_socket: unix:///var/run/containerd/containerd.sock

# VRRP and HAProxy
interface_name: "enp0s8"
virtual_ip: "192.168.178.100"
haproxy_frontend_password: "121password121"


# Disk
# disk: "/dev/sdb"
# partition: "/dev/sdb1"
# volume_group: "data_vg"
# logical_volume: "data_lv"
# filesystem_type: "xfs"
# mount_point: "/data"