# General
install_ansible_modules: "true"
disable_transparent_huge_pages: "true"
setup_interface: "false"

#SSH
ssh_port: 2222

# Network Calico

calico_operator_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml"
calico_crd_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml"
pod_network_cidr: "192.168.0.0/16"

# DNS

resolv_nameservers: [178.22.122.100, 185.51.200.2] # 403.online

# Sanction shekan

use_beshkaf: "true" # change it to "false" if you are outside of iran

# Docker

docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_gpg_key_path: "/etc/apt/keyrings/docker.gpg"
docker_apt_repo: "https://download.docker.com/linux/ubuntu"

# Kubernetes

kubernetes_gpg_keyring_path: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
kubernetes_gpg_key_url: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key"
kubernetes_apt_repo: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/"
k8s_version: "1.28.5"
# Disk
# disk: "/dev/sdb"
# partition: "/dev/sdb1"
# volume_group: "data_vg"
# logical_volume: "data_lv"
# filesystem_type: "xfs"
# mount_point: "/data"

# CRI

cri_socket: unix:///var/run/containerd/containerd.sock

# install_docker: "true"
# docker_version: 5:20.10.12~3-0~debian-bullseye
# containerd_version: 1.4.13-1
# docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
# docker_apt_gpg_key: https://download.docker.com/linux/debian/gpg
# docker_apt_ignore_key_error: true

# Kubernetes
# k8s_version: 1.21.10-00
# kubernetes_apt_repository: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
# kubernetes_apt_gpg_key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

# Docker compose options
# docker_install_compose: true
# docker_compose_version: "1.29.2"
# docker_compose_path:

# HPE server packages
# hp_package_list:
#   - hponcfg-5.6.0-0_amd64.deb
#   # - hp-health_10.80-1874.10_amd64.deb
#   # - ssacli-5.20-8.0_amd64.deb
# hp_apt_repository: http://downloads.linux.hpe.com/SDR/repo/mcp/pool/non-free